services:
  - type: web
    name: anime-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: BOT_TOKEN
        value: "8551657001:AAHSG0veXc6s2-27a_dp7wp3KsTDS80kH3A"
      - key: ADMIN_IDS 
        value: "7179662037,2025400572"
      - key: DATABASE_URL
        fromDatabase:
          name: anime-bot-db
          property: connectionString
      - key: WEBHO